# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_cat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cat',
        ),
    ]
