# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0007_auto_20170113_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency_pairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currensy_1', models.CharField(choices=[('CRYPTO', (('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('XRP', 'Ripple'), ('XMR', 'Monero'), ('DASH', 'Dash'), ('ZEC', 'Zcash'), ('EMC', 'Emercoin'))), ('FIAT', (('USD', 'US Dollar'), ('EUR', 'Euro'), ('CNY', 'Chinese yuan'), ('RUB', 'Russian Rouble')))], max_length=3)),
                ('currensy_2', models.CharField(choices=[('CRYPTO', (('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('XRP', 'Ripple'), ('XMR', 'Monero'), ('DASH', 'Dash'), ('ZEC', 'Zcash'), ('EMC', 'Emercoin'))), ('FIAT', (('USD', 'US Dollar'), ('EUR', 'Euro'), ('CNY', 'Chinese yuan'), ('RUB', 'Russian Rouble')))], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Currency_pairs_Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(choices=[('BTC-E', 'BTC-E'), ('xBTCe', 'xBTCe'), ('Poloniex', 'Poloniex'), ('YoBit', 'YoBit'), ('Bitfinex', 'Bitfinex'), ('Bittrex', 'Bittrex'), ('Huobi', 'Huobi'), ('QuadrigaCX', 'QuadrigaCX'), ('Exmo', 'Exmo'), ('Kraken', 'Kraken'), ('Cryptopia', 'Cryptopia'), ('DABTC', 'DABTC'), ('BTER', 'BTER'), ('Bitstamp', 'Bitstamp'), ('GDAX', 'GDAX'), ('Coincheck', 'Coincheck'), ('HitBTC', 'HitBTC'), ('Yuanbao', 'Yuanbao'), ('Korbit', 'Korbit'), ('Livecoin', 'Livecoin'), ('Gemini', 'Gemini'), ('itBit', 'itBit'), ('CEX.IO', 'CEX.IO'), ('CoinsBank', 'CoinsBank'), ('Bitcoin.de', 'Bitcoin.de'), ('Coinbase', 'Coinbase'), ('OKCoin', 'OKCoin'), ('BTC38', 'BTC38'), ('Jubi', 'Jubi'), ('OkCoin Intl', 'OkCoin Intl'), ('Ripple Gateways', 'Ripple Gateways'), ('Bitcoin Indonesia', 'Bitcoin Indonesia'), ('ShapeShift', 'ShapeShift')], max_length=20)),
            ],
        ),
    ]
