# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20170113_2009'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bets',
            new_name='Bet',
        ),
    ]
