# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 19:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20170116_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet_usd_btc',
            name='spread',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='bet_usd_btc',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 16, 19, 4, 55, 572828)),
        ),
    ]
