# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 19:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20170116_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet_usd_btc',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 16, 19, 7, 7, 45003)),
        ),
    ]
