# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 19:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20170116_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet_usd_btc',
            name='highest_bid',
            field=models.DecimalField(decimal_places=6, max_digits=7),
        ),
        migrations.AlterField(
            model_name='bet_usd_btc',
            name='lowest_ask',
            field=models.DecimalField(decimal_places=6, max_digits=7),
        ),
        migrations.AlterField(
            model_name='bet_usd_btc',
            name='spread',
            field=models.DecimalField(decimal_places=6, max_digits=7),
        ),
        migrations.AlterField(
            model_name='bet_usd_btc',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 16, 19, 13, 57, 974327)),
        ),
    ]
