# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20170116_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet_usd_btc',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
