# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20170117_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet_usd_btc',
            name='nice_spread',
            field=models.BooleanField(default=False),
        ),
    ]
